version: '3.8'

services:
  ca:
    image: smallstep/step-ca:0.25.3-rc5
    container_name: step-ca-server
    ports:
      - "8443:443"
      - "9000:9000"
    volumes:
      - /app-data/step-ca:/home/step
    restart: always
    environment:
      DOCKER_STEPCA_INIT_NAME: labzio
      DOCKER_STEPCA_INIT_DNS_NAMES: localhost,10.23.1.39
      DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT: "true"
      DOCKER_STEPCA_INIT_PASSWORD: "p@55w0rD"
      DOCKER_STEPCA_INIT_ACME: "acme"
      DOCKER_STEPCA_INIT_PROVISIONER_NAME: "admin-prov"

